.\ahkpm-modules\github.com\pstaszko\AHK_Compiler\Ahk2Exe.exe /base ".\ahkpm-modules\github.com\pstaszko\AHK_Compiler\v1.1.37.02\Unicode 64-bit.bin" /in "HotSocket_Server.ahk"
.\ahkpm-modules\github.com\pstaszko\AHK_Compiler\Ahk2Exe.exe /base ".\ahkpm-modules\github.com\pstaszko\AHK_Compiler\v1.1.37.02\Unicode 64-bit.bin" /in "MQTT_Pub.ahk"
.\ahkpm-modules\github.com\pstaszko\AHK_Compiler\Ahk2Exe.exe /base ".\ahkpm-modules\github.com\pstaszko\AHK_Compiler\v1.1.37.02\Unicode 64-bit.bin" /in "MQTT_Sub.ahk"
.\ahkpm-modules\github.com\pstaszko\AHK_Compiler\Ahk2Exe.exe /base ".\ahkpm-modules\github.com\pstaszko\AHK_Compiler\v1.1.37.02\Unicode 64-bit.bin" /in "PortableRunner.ahk"
.\ahkpm-modules\github.com\pstaszko\AHK_Compiler\Ahk2Exe.exe /base ".\ahkpm-modules\github.com\pstaszko\AHK_Compiler\v1.1.37.02\Unicode 64-bit.bin" /in "RunVanilla.ahk"
