g_2_AutomaticBehaviors(GroupName, WinTitle, WinText="", Label="", ExcludeTitle="", ExcludeText=""){
	MyGroupAdd(GroupName, WinTitle, WinText, Label, ExcludeTitle, ExcludeText)
}
g_2_AutomaticBehaviors_End(GroupName, WinTitle, WinText="", Label="", ExcludeTitle="", ExcludeText=""){
	MyGroupAdd(GroupName, WinTitle, WinText, Label, ExcludeTitle, ExcludeText)
}
g_4_KeyBehaviors(GroupName, WinTitle, WinText="", Label="", ExcludeTitle="", ExcludeText=""){
	MyGroupAdd(GroupName, WinTitle, WinText, Label, ExcludeTitle, ExcludeText)
}
g_4_KeyBehaviors_End(GroupName, WinTitle, WinText="", Label="", ExcludeTitle="", ExcludeText=""){
	MyGroupAdd(GroupName, WinTitle, WinText, Label, ExcludeTitle, ExcludeText)
}
g_1_ProgramGroups(GroupName, WinTitle, WinText="", Label="", ExcludeTitle="", ExcludeText=""){
	if contains(wintitle,"ahk_group")
		DumpParams("Error with group using group before group is a group",GroupName,WinTitle)
	MyGroupAdd(GroupName, WinTitle, WinText, Label, ExcludeTitle, ExcludeText)
}
g_1_ProgramGroups_End(GroupName, WinTitle, WinText="", Label="", ExcludeTitle="", ExcludeText=""){
	MyGroupAdd(GroupName, WinTitle, WinText, Label, ExcludeTitle, ExcludeText)
}
g_2_ProgramGroups_End(GroupName, WinTitle, WinText="", Label="", ExcludeTitle="", ExcludeText=""){
	g_1_ProgramGroups_End(GroupName, WinTitle, WinText, Label, ExcludeTitle, ExcludeText)
}
g_3_OneOffProgramGroups(GroupName, WinTitle, WinText="", Label="", ExcludeTitle="", ExcludeText=""){
	MyGroupAdd(GroupName, WinTitle, WinText, Label, ExcludeTitle, ExcludeText)
}
g_3_OneOffProgramGroupsEnd(GroupName, WinTitle, WinText="", Label="", ExcludeTitle="", ExcludeText=""){
	MyGroupAdd(GroupName, WinTitle, WinText, Label, ExcludeTitle, ExcludeText)
}
MyGroupAdd(GroupNames, WinTitle, WinText="", Label="", ExcludeTitle="", ExcludeText=""){
	global
	if (GroupNames="")
	{
		AlertCallStack("mga fail 1")
	}
	loop parse, GroupNames,`,
	{
		GroupName:=A_LoopField
		altTitle:=WinTitle
		altTitle.Replace(" ","")
		altTitle.Replace("-","")
		altTitle.Replace("(","")
		altTitle.Replace(".","")
		altTitle.Replace("&","")
		altTitle.Replace(")","")
		altgrpname:=GroupName altTitle
		altgrpname:="altGroup_" altgrpname
		if !altgrpname
			AlertCallStack("mga fail 2")
		try
		{
			GroupAdd %GroupName%,%WinTitle%,%WinText%,%Label%,%ExcludeTitle%,%ExcludeText%
		} catch e {
			t("Failed to add " GroupName " in MyGroupAdd " a_scriptfullpath)
			;sleep 5000
		}

		try
		{
			GroupAdd %altgrpname%,%WinTitle%,%WinText%,%Label%,%ExcludeTitle%,%ExcludeText%
		} catch e {
			t(e)
		}

		WindowsForGroup:=MyGroups[GroupName]
		if !WindowsForGroup
			WindowsForGroup:={}
		ThisWindow:={}
		ThisWindow["WinTitle"]:=WinTitle
		ThisWindow["WinText"]:=WinText
		ThisWindow["Label"]:=Label
		ThisWindow["ExcludeTitle"]:=ExcludeTitle
		ThisWindow["ExcludeText"]:=ExcludeText
		WindowsForGroup[WinTitle]:=ThisWindow
		MyGroups[GroupName]:=WindowsForGroup
		z:=ThisWindow[WinText]

		GroupName:=altgrpname
		WindowsForGroup:=MyGroups[GroupName]
		if !WindowsForGroup
			WindowsForGroup:={}
		ThisWindow:={}
		ThisWindow["WinTitle"]:=WinTitle
		ThisWindow["WinText"]:=WinText
		ThisWindow["Label"]:=Label
		ThisWindow["ExcludeTitle"]:=ExcludeTitle
		ThisWindow["ExcludeText"]:=ExcludeText
		WindowsForGroup[WinTitle]:=ThisWindow
		MyGroups[GroupName]:=WindowsForGroup
		z:=ThisWindow[WinText]
	}
}
NewLoadGroups(){
	global
	if 1 ;Groups
	{
	;***************************************************************************************************************
	;GROUPS********************************************************************************************************
	;***************************************************************************************************************
	;Op: Distinct
	;Op: Sort
	;g_1_ProgramGroups("TypeSQLLogins","Connect ahk_exe devenv.exe","","","|") ;;DB Profile
	g_1_ProgramGroups("AbortRecursiveDive","Attach to Process ahk_class #32770 ahk_exe devenv.exe")
	g_1_ProgramGroups("AbortRecursiveDive","File Modification Detected ahk_class #32770 ahk_exe devenv.exe")
	g_1_ProgramGroups("AbortRecursiveDive","Microsoft Visual Studio ahk_class #32770 ahk_exe devenv.exe","been modified outside")
	g_1_ProgramGroups("AbortRecursiveDive","Microsoft Visual Studio ahk_class #32770 ahk_exe devenv.exe","Save changes to the following item")
	g_1_ProgramGroups("AbortRecursiveDive","Microsoft Visual Studio ahk_class #32770 ahk_exe devenv.exe","This file has been modified outside of the source editor.")
	g_1_ProgramGroups("AbortRecursiveDive","QuickWatch ahk_class #32770 ahk_exe devenv.exe")
	g_1_ProgramGroups("AbortRecursiveDive","Text Visualizer ahk_class #32770 ahk_exe devenv.exe")
	g_1_ProgramGroups("AHKtextEditor","AutoHotkey_L Help ahk_class HH Parent ahk_exe hh.exe")
	g_1_ProgramGroups("AHKtextEditor","Notepad++ ahk_class Notepad++ ahk_exe notepad++.exe")
	g_1_ProgramGroups("AHKtextEditor","SciTE ahk_class SciTEWindow")
	g_1_ProgramGroups("AllowControlTilde","Microsoft Excel ahk_class XLMAIN")
	g_1_ProgramGroups("BeyondCompare","ahk_exe BCompare.exe")
	g_1_ProgramGroups("BeyondCompare_VScompare","vctmp ahk_exe BCompare.exe")
	g_1_ProgramGroups("Brave","ahk_class Chrome_WidgetWin_1 ahk_exe brave.exe")
	g_1_ProgramGroups("Browsers","ahk_class Chrome_WidgetWin_1 ahk_exe brave.exe")
	g_1_ProgramGroups("Browsers","ahk_class OperaWindowClass ahk_exe Opera.exe",,,"ahk_class 32770")
	g_1_ProgramGroups("Browsers","ahk_class Qt5152QWindowIcon ahk_exe qutebrowser.exe")
	g_1_ProgramGroups("Browsers","ahk_exe chrome.exe",,,"ahk_class 32770")
	g_1_ProgramGroups("Browsers","ahk_exe Firefox.exe",,,"ahk_class 32770")
	g_1_ProgramGroups("Browsers","ahk_exe iexplore.exe",,,"ahk_class 32770")
	g_1_ProgramGroups("Browsers","ahk_exe Maxthon.exe",,,"ahk_class 32770")
	g_1_ProgramGroups("Browsers","ahk_exe opera.exe",,,"ahk_class 32770")
	g_1_ProgramGroups("Browsers","ahk_exe Safari.exe",,,"ahk_class 32770")
	g_1_ProgramGroups("Browsers","Firefox ahk_Group Firefox",,,"ahk_class 32770")
	g_1_ProgramGroups("Browsers","Google Chrome ahk_class Chrome_XPFrame",,,"ahk_class 32770")
	g_1_ProgramGroups("Browsers","Iron ahk_class Chrome_WidgetWin_0")
	g_1_ProgramGroups("Browsers","Log in to your PayPal account ahk_class Chrome_WidgetWin_1 ahk_exe Heroic.exe")
	g_1_ProgramGroups("ChaosControl","Chaos Control ahk_class Qt5QWindowOwnDCIcon ahk_exe ChaosControl.exe")
	g_1_ProgramGroups("CharDef", "A private chat with ahk_group Browsers")
	g_1_ProgramGroups("CharDef", "Agnaistic ahk_group Browsers")
	g_1_ProgramGroups("CharDef", "AI Character Editor")
	g_1_ProgramGroups("CharDef", "C:\Users\Paul\Desktop\Profiles\ ahk_class Notepad++ ahk_exe notepad++.exe")
	g_1_ProgramGroups("CharDef", "Chat with ahk_exe opera.exe")
	g_1_ProgramGroups("CharDef", "crushon ahk_group Browsers")
	g_1_ProgramGroups("CharDef", "CrushOn")
	g_1_ProgramGroups("CharDef", "PepHop AI")
	g_1_ProgramGroups("Chrome","ahk_exe chrome.exe")
	g_1_ProgramGroups("Chrome_AWS","Route 53 Management Console ahk_exe chrome.exe")
	g_1_ProgramGroups("Chrome_ConnectWise","ConnectWise ahk_exe chrome.exe")
	g_1_ProgramGroups("Chrome_Hiders","ahk_group GoogleMusic")
	g_1_ProgramGroups("Chrome_NWCWiki","Netcenter Web Team ahk_exe chrome.exe")
	g_1_ProgramGroups("Chrome_Wunderlist","- Wunderlist - Google Chrome ahk_exe chrome.exe")
	g_1_ProgramGroups("ClipMaster","ahk_exe ClipMaster")
	g_1_ProgramGroups("Clipmaster_SQL_Report","SQL Report ahk_exe ClipMaster.exe")
	g_1_ProgramGroups("Clipmaster_SQL_Report","SQL Report ahk_exe ClipMaster.vshost.exe")
	g_1_ProgramGroups("ConEmu","ahk_exe ConEmu.exe")
	g_1_ProgramGroups("ConEmu","ahk_exe ConEmu64.exe")
	g_1_ProgramGroups("CyberSentryComputerReadout","Cyber Sentry II ahk_exe Gui.exe")
	g_1_ProgramGroups("DatabaseUpdateEmail","Database Update ahk_class rctrl_renwnd32 ahk_exe OUTLOOK.EXE")
	g_1_ProgramGroups("DatabaseUpdateEmail","Distribution Database ahk_class rctrl_renwnd32 ahk_exe OUTLOOK.EXE")
	g_1_ProgramGroups("DataGrip","ahk_class SunAwtFrame ahk_exe datagrip64.exe")
	g_1_ProgramGroups("DevelopmentWindowsToMaximize","ahk_exe devenv.exe")
	g_1_ProgramGroups("DevelopmentWindowsToMaximize","ahk_exe scite.exe")
	g_1_ProgramGroups("DevelopmentWindowsToMaximize","ahk_exe ssms.exe")
	g_1_ProgramGroups("DocFetcher","ahk_class SWT_Window0 ahk_exe javaw.exe")
	g_1_ProgramGroups("EchelonGmail","Echelon.com ahk_group browsers")
	g_1_ProgramGroups("EchelonGmail","Single Sign On ahk_group browsers")
	g_1_ProgramGroups("Emacs","Emacs ahk_class Emacs ahk_exe emacs.exe")
	g_1_ProgramGroups("Emacs","Emacs ahk_class Emacs ahk_exe runemacs.exe")
	g_1_ProgramGroups("Everything","ahk_class EVERYTHING ahk_exe Everything.exe")
	g_1_ProgramGroups("Everything","ahk_class EVERYTHING_(1.5a) ahk_exe Everything64.exe")
	g_1_ProgramGroups("Everything","ahk_exe Everything64.exe")
	g_1_ProgramGroups("Excel","ahk_class XLMAIN ahk_exe EXCEL.EXE")
	g_1_ProgramGroups("Excel","ahk_exe Excel.exe")
	g_1_ProgramGroups("Explorer","ahk_class CabinetWClass")
	g_1_ProgramGroups("Explorer,Explorer_Files","ahk_class CabinetWClass")
	g_1_ProgramGroups("FilePicker","Open ahk_class #32770")
	g_1_ProgramGroups("FilePicker","Save As ahk_class #32770")
	g_1_ProgramGroups("Firefox","ahk_class MozillaUIWindowClass")
	g_1_ProgramGroups("Firefox","ahk_class MozillaWindowClass")
	g_1_ProgramGroups("FirefoxDialog","ahk_class MozillaDialogClass")
	g_1_ProgramGroups("FortiClient","ahk_exe FortiClient.exe")
	g_1_ProgramGroups("FSSConsole","ahk_class ConsoleWindowClass ahk_exe FSSConsole.exe")
	g_1_ProgramGroups("FSSConsole","FSS Console")
	g_1_ProgramGroups("FullScreenRDP","azsql19")
	g_1_ProgramGroups("FullScreenRDP","Cricket")
	g_1_ProgramGroups("FullScreenRDP","imacros")
	g_1_ProgramGroups("Games","shapez 2 ahk_class UnityWndClass")
	g_1_ProgramGroups("Games","ahk_exe DSPGAME.exe")
	g_1_ProgramGroups("Games","ahk_exe FarCryNewDawn.exe")
	g_1_ProgramGroups("Games","ahk_exe HoloCure.exe")
	g_1_ProgramGroups("Games","ahk_exe NMS.exe") ;no man's sky
	g_1_ProgramGroups("Games","ahk_exe StarWarsSquadrons.exe")
	g_1_ProgramGroups("Games","ahk_exe theHunterCotW_F.exe")
	g_1_ProgramGroups("Games","Dying Light ahk_class techland_game_class ahk_exe DyingLightGame.exe")
	g_1_ProgramGroups("Games","shapez 2 ahk_class UnityWndClass ahk_exe shapez 2.exe")
	g_1_ProgramGroups("Games","STAR WARS Jedi: Fallen Order ahk_class UnrealWindow ahk_exe starwarsjedifallenorder.exe")
	g_1_ProgramGroups("GoogleMusic","Google Play Music - Google Chrome ahk_class Chrome_WidgetWin_1 ahk_exe chrome.exe")
	g_1_ProgramGroups("GoogleMusic","YouTube - Google Chrome ahk_exe chrome.exe")
	g_1_ProgramGroups("GoToCMSFolderFromTitle","CM ahk_class rctrl_renwnd32 ahk_exe OUTLOOK.EXE")
	g_1_ProgramGroups("GoToCMSFolderFromTitle","Help Desk Issue Tracking  ahk_class MozillaWindowClass ahk_exe firefox.exe")
	g_1_ProgramGroups("GoToCMSFolderFromTitle","Home - Information Technology (Private) ahk_group Browsers")
	g_1_ProgramGroups("GoToCMSFolderFromTitle","IT Change Management and SDLC ahk_class MozillaWindowClass ahk_exe firefox.exe")
	g_1_ProgramGroups("HideOnCycleEXE","CiceroUIWndFrame ahk_class CiceroUIWndFrame ahk_exe devenv.exe")
	g_1_ProgramGroups("HideOnCycleEXE","theAwtToolkitWindow ahk_class SunAwtToolkit ahk_exe datagrip64.exe")
	g_1_ProgramGroups("IntelliJIdea","ahk_class SunAwtFrame ahk_exe idea64.exe")
	g_1_ProgramGroups("JIRA","JIRA ahk_group Browsers",,,"System Dashboard") ;;work
	g_1_ProgramGroups("JsonView","JSON Viewer ahk_exe JsonView.exe")
	g_1_ProgramGroups("KeepHidden","ahk_class Net UI Tool Window")
	g_1_ProgramGroups("KeepHidden","ahk_class OfficeToastWndClass")
	g_1_ProgramGroups("KeepHidden","Outlook Send/Receive Progress ahk_class #32770 ahk_exe OUTLOOK.EXE")
	g_1_ProgramGroups("Krita","ahk_exe krita.exe")
	g_1_ProgramGroups("LaterConsoleBeta","Later Beta ahk_class ConsoleWindowClass ahk_exe cmd.exe")
	g_1_ProgramGroups("LaterConsoleBeta","Later Beta ahk_class ConsoleWindowClass ahk_exe LaterConsole.exe")
	g_1_ProgramGroups("LaterConsoleProd","Later Prod ahk_class ConsoleWindowClass ahk_exe cmd.exe")
	g_1_ProgramGroups("LaterConsoleProd","Later Prod ahk_class ConsoleWindowClass ahk_exe LaterConsole.exe")
	g_1_ProgramGroups("LINQPad","LINQPad ahk_exe LINQPad.exe")
	g_1_ProgramGroups("Locate,Explorer_Files","ahk_class #32770 ahk_exe locate32.exe")cccccccccc
	g_1_ProgramGroups("LuaMacros","ahk_class Window ahk_exe LuaMacros.exe")
	g_1_ProgramGroups("LuaMacrosEditor","functions.lua ahk_class Notepad++ ahk_exe Notepad++.exe")
	g_1_ProgramGroups("LuaMacrosEditor","x.lua ahk_class Notepad++ ahk_exe Notepad++.exe")
	g_1_ProgramGroups("MatrixOS","Matrix OS ahk_class ConsoleWindowClass ahk_exe cmd.exe")
	g_1_ProgramGroups("MatrixOS","Matrix OS ahk_class ConsoleWindowClass ahk_exe MatrixOS.exe")
	g_1_ProgramGroups("MatrixOS","Matrix OS ahk_class ConsoleWindowClass ahk_exe VsDebugConsole.exe")
	g_1_ProgramGroups("MatrixOS","MatrixNexus ahk_class ConsoleWindowClass ahk_exe cmd.exe")
	g_1_ProgramGroups("MatrixOS","MatrixNexus ahk_class ConsoleWindowClass ahk_exe MatrixNexus.exe")
	g_1_ProgramGroups("MatrixOS","MatrixNexus ahk_class ConsoleWindowClass ahk_exe VsDebugConsole.exe")
	g_1_ProgramGroups("Maxthon","ahk_class Second Life ahk_exe SecondLifeViewer.exe")
	g_1_ProgramGroups("Maxthon","ahk_exe Maxthon.exe")
	g_1_ProgramGroups("MButton","ahk_exe DSPGAME.exe")
	g_1_ProgramGroups("MButton","ahk_exe farcry5.exe")
	g_1_ProgramGroups("MButton","ahk_exe NMS.exe") ;no man's sky
	g_1_ProgramGroups("MButton","SketchUp ahk_exe SketchUp.exe")
	g_1_ProgramGroups("MButton","Skyrim ahk_class Skyrim ahk_exe TESV.exe")
	g_1_ProgramGroups("MediaPlayerClassic","ahk_class MediaPlayerClassicW")
	g_1_ProgramGroups("MeterFirmwareDoc","Meter FW Func Spec ahk_group browsers") ;;work
	g_1_ProgramGroups("MicrosoftSignInWindow","Accounts ahk_class NUIDialog ahk_exe devenv.exe")
	g_1_ProgramGroups("MicrosoftSignInWindow","Sign in to your ahk_exe devenv.exe")
	g_1_ProgramGroups("Minecraft","Create ahk_class GLFW30 ahk_exe javaw.exe")
	g_1_ProgramGroups("Minecraft","FTB Ultimate ahk_class SunAwtFrame ahk_exe javaw.exe")
	g_1_ProgramGroups("Minecraft","Minecraft 1 ahk_exe javaw.exe")
	g_1_ProgramGroups("Minecraft","Minecraft ahk_class GLFW30 ahk_exe javaw.exe")
	g_1_ProgramGroups("Minecraft","Minecraft ahk_exe javaw.exe")
	g_1_ProgramGroups("Minecraft","Tekkit ahk_exe javaw.exe")
	g_1_ProgramGroups("MinecraftServer","Minecraft server ahk_class SunAwtFrame ahk_exe javaw.exe")
	g_1_ProgramGroups("MinorWindows","- Appointment")
	g_1_ProgramGroups("MinorWindows","- Meeting ahk_class rctrl_renwnd32 ahk_exe OUTLOOK.EXE")
	g_1_ProgramGroups("MinorWindows","- Meeting Occurrence ahk_class rctrl_renwnd32 ahk_exe OUTLOOK.EXE")
	g_1_ProgramGroups("MinorWindows","- Mozilla Thunderbird ahk_class MozillaWindowClass ahk_exe thunderbird.exe")
	g_1_ProgramGroups("MinorWindows","- SciTE - Jump ahk_class SciTEWindow ahk_exe SCITE.EXE")
	g_1_ProgramGroups("MinorWindows",".formatted.xml ahk_exe foxe.exe")
	g_1_ProgramGroups("MinorWindows","Active Directory Users and Computers")
	g_1_ProgramGroups("MinorWindows","Active Window Info ahk_class AutoHotkeyGUI ahk_exe AU3_Spy.exe")
	g_1_ProgramGroups("MinorWindows","ahk_class #32770 ahk_exe AutoHotkey.exe")
	g_1_ProgramGroups("MinorWindows","ahk_class CabinetWClass")
	g_1_ProgramGroups("MinorWindows","ahk_class ConsoleWindowClass ahk_exe chromedriver.exe")
	g_1_ProgramGroups("MinorWindows","ahk_class ConsoleWindowClass ahk_exe IEDriverServer.exe")
	g_1_ProgramGroups("MinorWindows","ahk_class ExploreWClass")
	g_1_ProgramGroups("MinorWindows","ahk_class PrintUI_PrinterQueue")
	g_1_ProgramGroups("MinorWindows","ahk_class SciCalc")
	g_1_ProgramGroups("MinorWindows","ahk_class Shell_Dialog ahk_exe emlviewer.exe")
	g_1_ProgramGroups("MinorWindows","ahk_class SUMATRA_PDF_FRAME")
	g_1_ProgramGroups("MinorWindows","ahk_exe notepad.exe")
	g_1_ProgramGroups("MinorWindows","ahk_exe Probe.exe")
	g_1_ProgramGroups("MinorWindows","ahk_exe pushbullet_client.exe")
	g_1_ProgramGroups("MinorWindows","ahk_exe SnippingTool.exe")
	g_1_ProgramGroups("MinorWindows","AHK_PS_Temp_ahk_class IEFrame ahk_exe iexplore.exe")
	g_1_ProgramGroups("MinorWindows","AHKparserResults.txt - SciTE ahk_class SciTEWindow")
	g_1_ProgramGroups("MinorWindows","AutoHotkey_ ahk_class #32770 ahk_exe AutoHotkey.exe")
	g_1_ProgramGroups("MinorWindows","C:\Users\Paul\scoop\shims\lazygit.exe ahk_class ConsoleWindowClass ahk_exe lazygit.exe")
	g_1_ProgramGroups("MinorWindows","Calculator ahk_class ApplicationFrameWindow ahk_exe ApplicationFrameHost.exe")
	g_1_ProgramGroups("MinorWindows","Calculator ahk_class CalcFrame")
	g_1_ProgramGroups("MinorWindows","ClipmasterOutput.txt")
	g_1_ProgramGroups("MinorWindows","Download complete ahk_class #32770")
	g_1_ProgramGroups("MinorWindows","Downloads ahk_class MozillaWindowClass")
	g_1_ProgramGroups("MinorWindows","Find in All Tabs ahk_exe firefox.exe")
	g_1_ProgramGroups("MinorWindows","Git Command Progress - TortoiseGit ahk_class #32770 ahk_exe TortoiseGitProc.exe","Success")
	g_1_ProgramGroups("MinorWindows","gitk ahk_class TkTopLevel ahk_exe wish.exe")
	g_1_ProgramGroups("MinorWindows","JSON Viewer ahk_exe JsonView.exe")
	g_1_ProgramGroups("MinorWindows","Later Response ahk_exe scite.exe")
	g_1_ProgramGroups("MinorWindows","Left ahk_class WinMergeWindowClassW ahk_exe WinMergeU.exe")
	g_1_ProgramGroups("MinorWindows","Log Messages - TortoiseGit ahk_class #32770 ahk_exe TortoiseGitProc.exe")
	g_1_ProgramGroups("MinorWindows","MessageLog.txt")
	g_1_ProgramGroups("MinorWindows","MissedNotificationWindow ahk_exe Growl.exe")
	g_1_ProgramGroups("MinorWindows","notepadpopup.txt ahk_class SciTEWindow ahk_exe SciTE.exe")
	g_1_ProgramGroups("MinorWindows","Paul.ini ahk_class SciTEWindow ahk_exe SCITE.EXE")
	g_1_ProgramGroups("MinorWindows","Picker ahk_exe MatrixNexus.exe")
	g_1_ProgramGroups("MinorWindows","Picker ahk_exe MatrixOS.exe")
	g_1_ProgramGroups("MinorWindows","Print Preview ahk_class Internet Explorer_TridentDlgFrame ahk_exe iexplore.exe")
	g_1_ProgramGroups("MinorWindows","Properties ahk_class #32770 ahk_exe ProcessHacker.exe")
	g_1_ProgramGroups("MinorWindows","results.txt - SciTE ahk_class SciTEWindow")
	g_1_ProgramGroups("MinorWindows","Revision Graph - TortoiseGit ahk_class #32770 ahk_exe TortoiseGitProc.exe")
	g_1_ProgramGroups("MinorWindows","scratch.txt ahk_class SciTEWindow ahk_exe SCITE.EXE")
	g_1_ProgramGroups("MinorWindows","Sumatra")
	g_1_ProgramGroups("MinorWindows","TeamViewer ahk_class TV_ChatWindow ahk_exe TeamViewer.exe")
	g_1_ProgramGroups("MinorWindows","TortoiseGitMerge ahk_exe TortoiseGitMerge.exe")
	g_1_ProgramGroups("MinorWindows","vctmp ahk_class TViewForm.UnicodeClass ahk_exe BCompare.exe")
	g_1_ProgramGroups("MinorWindows","View Downloads - Windows Internet Explorer ahk_class #32770 ahk_exe iexplore.exe")
	g_1_ProgramGroups("MinorWindows","Vnc Authentication ahk_class #32770 ahk_exe tvnviewer.exe")
	g_1_ProgramGroups("MinorWindows","Windows Help and Support ahk_class HelpPane")
	g_1_ProgramGroups("MinorWindows","Windows Photo Viewer ahk_class Photo_Lightweight_Viewer ahk_exe DllHost.exe")
	g_1_ProgramGroups("MinorWindows","WinMerge - [vctm+++^!ahk_class WinMergeWindowClassW ahk_exe WinMergeU.exe")
	g_1_ProgramGroups("MinorWindows","WinMerge ahk_class WinMergeWindowClassW ahk_exe Winmergeu.exe")
	g_1_ProgramGroups("MinorWindows","Winmerge_Expected - Winmerge_Actual ahk_exe WinMergeU.exe")
	g_1_ProgramGroups("MinorWindows","WordPad")
	g_1_ProgramGroups("MinorWindowsLevel2","ahk_exe AgentRansack.exe")
	g_1_ProgramGroups("MinorWindowsLevel2","ahk_exe ClipMaster.exe")
	g_1_ProgramGroups("MinorWindowsLevel2","ahk_group IE")
	g_1_ProgramGroups("MinorWindowsLevel2","ahk_group PDFReader")
	g_1_ProgramGroups("MinorWindowsLevel2","AutoHotkey ahk_class HH Parent ahk_exe hh.exe")
	g_1_ProgramGroups("MinorWindowsLevel2","files found - [Search:") ;Agent Ransack
	g_1_ProgramGroups("MinorWindowsLevel2","Growl ahk_exe Growl.exe")
	g_1_ProgramGroups("MinorWindowsLevel2","Locate ahk_class #32770 ahk_exe locate32.exe")
	g_1_ProgramGroups("MinorWindowsLevel2","Microsoft Help Viewer ahk_exe HlpViewer.exe")
	g_1_ProgramGroups("MinorWindowsLevel2","Paul.ini - SciTE ahk_class SciTEWindow ahk_exe SCITE.EXE")
	g_1_ProgramGroups("MinorWindowsLevel2","Prestart Checklist.txt - SciTE ahk_class SciTEWindow")
	g_1_ProgramGroups("MinorWindowsLevel2","Regex Pad")
	g_1_ProgramGroups("MinorWindowsLevel2","Run ahk_class #32770 ahk_exe explorer.exe")
	g_1_ProgramGroups("MinorWindowsLevel2","Windows Photo Viewer ahk_class Photo_Lightweight_Viewer ahk_exe DllHost.exe")
	g_1_ProgramGroups("MoveIdleMouse","Console Session ahk_exe Kaseya Remote Control.exe")
	g_1_ProgramGroups("MSAccess","Microsoft Access")
	g_1_ProgramGroups("MSIE","ahk_class IEFrame")
	g_1_ProgramGroups("MTD","ahk_exe mbem.exe")
	g_1_ProgramGroups("MTD","ahk_group ReportSolution")
	g_1_ProgramGroups("MTD_2","Report Manager - Mozilla Firefox ahk_class MozillaWindowClass ahk_exe firefox.exe")
	g_1_ProgramGroups("NeedyPrograms","* SciTE ahk_class SciTEWindow ahk_exe SCITE.EXE")
	g_1_ProgramGroups("NeedyPrograms","ahk_exe excel.EXE")
	g_1_ProgramGroups("NeedyPrograms","ahk_exe outlook.EXE")
	g_1_ProgramGroups("NeedyPrograms","ahk_exe winword.EXE")
	g_1_ProgramGroups("NeedyPrograms","devenv.exe")
	g_1_ProgramGroups("NeedyPrograms","KeePass ahk_exe KeePass.exe")
	g_1_ProgramGroups("NetBeans","Editor ahk_class SunAwtFrame ahk_exe javaw.exe")
	g_1_ProgramGroups("NetBeans","Editor ahk_class SunAwtFrame ahk_exe netbeans64.exe")
	g_1_ProgramGroups("NetBeans","NetBeans ahk_class SunAwtFrame ahk_exe javaw.exe")
	g_1_ProgramGroups("NetBeans","NetBeans ahk_class SunAwtFrame ahk_exe netbeans.exe")
	g_1_ProgramGroups("NetBeans","NetBeans ahk_class SunAwtFrame ahk_exe netbeans64.exe")
	g_1_ProgramGroups("NetBeans_Dialog","ahk_class SunAwtDialog ahk_exe netbeans64.exe")
	g_1_ProgramGroups("NetBeans_FindInProjects","Find in Projects ahk_group NetBeans_Dialog")
	g_1_ProgramGroups("NoCycleOnEXE","CiceroUIWndFrame ahk_class CiceroUIWndFrame ahk_exe devenv.exe")
	g_1_ProgramGroups("NoCycleOnEXE","theAwtToolkitWindow ahk_class SunAwtToolkit ahk_exe datagrip64.exe")
	g_1_ProgramGroups("NoMansSky","ahk_exe NMS.exe") ;no man's sky
	g_1_ProgramGroups("NoMax","ahk_exe autohotkey.exe")
	g_1_ProgramGroups("NoMaximizeOffset","ahk_class CabinetWClass")
	g_1_ProgramGroups("NoMinimizer","ahk_class Shell_TrayWnd")
	g_1_ProgramGroups("NoResearch","ahk_exe excel.exe")
	g_1_ProgramGroups("NoResearch","ahk_exe onenote.exe")
	g_1_ProgramGroups("NoResearch","ahk_exe outlook.exe")
	g_1_ProgramGroups("NoResearch","ahk_exe winword.exe")
	g_1_ProgramGroups("NPP","ahk_exe notepad++.exe")
	g_1_ProgramGroups("Obsidian","ahk_exe obsidian.exe")
	g_1_ProgramGroups("Office","ahk_exe EXCEL.EXE")
	g_1_ProgramGroups("Office","ahk_exe MSACCESS.EXE")
	g_1_ProgramGroups("Office","ahk_exe MSPUB.EXE")
	g_1_ProgramGroups("Office","ahk_exe ONENOTE.EXE")
	g_1_ProgramGroups("Office","ahk_exe OUTLOOK.EXE")
	g_1_ProgramGroups("Office","ahk_exe POWERPNT.EXE")
	g_1_ProgramGroups("Office","ahk_exe VISIO.EXE")
	g_1_ProgramGroups("Office","ahk_exe WINWORD.EXE")
	g_1_ProgramGroups("OfficeWindowsToMaximize","Word ahk_class OpusApp ahk_exe WINWORD.EXE")
	g_1_ProgramGroups("Outlook_Calendar","Calendar - ahk_class rctrl_renwnd32 ahk_exe OUTLOOK.EXE")
	g_1_ProgramGroups("OutlookEmail","ahk_class rctrl_renwnd32","","","paul.staszko@netcenter.net")
	g_1_ProgramGroups("PDFReader","ahk_class AcrobatSDIWindow")
	g_1_ProgramGroups("PDFReader","ahk_exe Foxit Reader.exe")
	g_1_ProgramGroups("PhotoViewer","Windows Photo Viewer ahk_class Photo_Lightweight_Viewer ahk_exe dllhost.exe")
	g_1_ProgramGroups("PlanDoc","Plan ahk_class MozillaWindowClass ahk_exe kompozer.exe")
	g_1_ProgramGroups("PlanDoc","plan.rtf")
	g_1_ProgramGroups("PlanDoc","plan.txt ahk_exe scite.exe")
	g_1_ProgramGroups("PowerBI","ahk_exe PBIDesktop.exe")
	g_1_ProgramGroups("PowerBI_Desktop","- Power BI Desktop ahk_exe PBIDesktop.exe")
	g_1_ProgramGroups("PowerBI_QueryEditor","- Query Editor ahk_exe PBIDesktop.exe")
	g_1_ProgramGroups("PowerGUI","ahk_exe ScriptEditor.exe")
	g_1_ProgramGroups("PowerGUI_FindAndReplace","Find & Replace ahk_exe ScriptEditor.exe")
	g_1_ProgramGroups("PowerGUI_FindAndReplace","Find/Replace ahk_exe ScriptEditor.exe")
	g_1_ProgramGroups("PowerShell","ahk_class ConsoleWindowClass ahk_exe pwsh.exe","","","PS: BackgroundPowerShell")
	g_1_ProgramGroups("PowerShell","PS ahk_group ConEmu")
	g_1_ProgramGroups("PowerShellCore","ahk_class ConsoleWindowClass ahk_exe pwsh.exe","","","PS: BackgroundPowerShell")
	g_1_ProgramGroups("PowerShellEditor","ahk_exe powershell_ise.exe")
	g_1_ProgramGroups("PowerShellEditor","ahk_group PowerGUI")
	g_1_ProgramGroups("PowerShellEditor","PowerShell ahk_group VisualStudio")
	g_1_ProgramGroups("PowershellTerminal","Administrator: Windows PowerShell ahk_class CASCADIA_HOSTING_WINDOW_CLASS ahk_exe WindowsTerminal.exe")
	g_1_ProgramGroups("PowershellTerminal","Wave ahk_class Chrome_WidgetWin_1 ahk_exe Wave.exe")
	g_1_ProgramGroups("PowershellTerminal","ahk_class VirtualConsoleClass ahk_exe ConEmu64.exe")
	g_1_ProgramGroups("PowershellTerminal","Windows Terminal ahk_class CASCADIA_HOSTING_WINDOW_CLASS ahk_exe WindowsTerminal.exe")
	g_1_ProgramGroups("ProcessHacker","Process Hacker ahk_class MainWindowClassName ahk_exe ProcessHacker.exe")
	g_1_ProgramGroups("Rambox","Rambox ahk_exe Rambox.exe")
	g_1_ProgramGroups("RemoteDesktop","- Microsoft Virtual PC 2007")
	g_1_ProgramGroups("RemoteDesktop","- Remote Desktop")
	g_1_ProgramGroups("RemoteDesktop","Virtual Machine Remote")
	g_1_ProgramGroups("RemoteDesktop","VMware Workstation ahk_class VMPlayerFrame ahk_exe vmplayer.exe")
	g_1_ProgramGroups("RemoteDesktopWindow","Remote Desktop Connection ahk_class TscShellContainerClass")
	g_1_ProgramGroups("Rider","ahk_class SunAwtFrame ahk_exe rider64.exe")
	g_1_ProgramGroups("RotateBucket","ahk_exe winword.exe")
	g_1_ProgramGroups("SampleApp","ahk_exe SampleUtilityApplication.exe")
	g_1_ProgramGroups("SampleApp","ahk_exe SampleUtilityApplication.vshost.exe")
	g_1_ProgramGroups("SciTE","SciTE ahk_class SciTEWindow")
	g_1_ProgramGroups("SciTE_FindOrReplaceDialog","Find ahk_class #32770 ahk_exe SCITE.EXE","","","","Files")
	g_1_ProgramGroups("SciTE_FindOrReplaceDialog","Replace ahk_class #32770 ahk_exe SCITE.EXE")
	g_1_ProgramGroups("Slack","ahk_class Chrome_WidgetWin_1 ahk_exe slack.exe")
	g_1_ProgramGroups("SourceGear"," DiffMerge ahk_exe sgdm.exe")
	g_1_ProgramGroups("Splashtop","ahk_exe strwindt.exe")
	g_1_ProgramGroups("SplashtopRemote","ahk_exe strwinclt.exe")
	g_1_ProgramGroups("Spotify","ahk_class Chrome_WidgetWin_0 ahk_exe Spotify.exe")
	g_1_ProgramGroups("SQLManagementStudio","ahk_exe Ssms.exe")
	g_1_ProgramGroups("SQLManagementStudio","Microsoft SQL Server Management Studio ahk_class wndclass_desked_gsk")
	g_1_ProgramGroups("SQLManagementStudio","Microsoft SQL Server Management Studio ahk_exe Ssms.exe")
	g_1_ProgramGroups("SQLManagementStudio","Microsoft SQL Server Management Studio ahk_exe Ssms.exe","`)`)")
	g_1_ProgramGroups("SSDT","Schemas ahk_exe devenv.exe")
	g_1_ProgramGroups("SSMS_DEVENV","ahk_exe devenv.exe")
	g_1_ProgramGroups("SSMS_DEVENV","ahk_exe ssms.exe")
	g_1_ProgramGroups("StarTrekOnline","GameClient ahk_class CrypticWindowClass ahk_exe GameClient.exe")
	g_1_ProgramGroups("SuperPowerClose","ahk_class rctrl_renwnd32 ahk_exe OUTLOOK.EXE")
	g_1_ProgramGroups("SuperPowerClose","ahk_exe RelexForms.exe")
	g_1_ProgramGroups("SuperPowerHide","Oculus ahk_exe OculusClient.exe")
	g_1_ProgramGroups("SystemInformer","ahk_class MainWindowClassName ahk_exe SystemInformer.exe")
	g_1_ProgramGroups("TeamViewer","TeamViewer ahk_class #32770")
	g_1_ProgramGroups("TightVNC","TightVNC Viewer ahk_class TvnWindowClass ahk_exe tvnviewer.exe")
	g_1_ProgramGroups("TypeSQLLogins","Connect to ahk_exe profiler.exe","","","|") ;;DB Profile
	g_1_ProgramGroups("TypeSQLLogins","Connect to ahk_exe ssms.exe","","","|") ;;DB Profile
	g_1_ProgramGroups("TypeSQLLogins","SQL Server Login ahk_class #32770 ahk_exe MSACCESS.EXE")
	g_1_ProgramGroups("UIauto","UIauto ahk_exe devenv.exe")
	g_1_ProgramGroups("UnMonitoredWindows","ahk_exe growl.exe")
	g_1_ProgramGroups("VBFile",".bas ( ahk_exe devenv.exe")
	g_1_ProgramGroups("VBFile",".cls ( ahk_exe devenv.exe")
	g_1_ProgramGroups("VBFile",".vb ( ahk_exe devenv.exe")
	g_1_ProgramGroups("VideoGame","ahk_exe SpaceEngineers.exe")
	g_1_ProgramGroups("VisualStudio","ahk_exe DevEnv.exe")
	g_1_ProgramGroups("VisualStudio","ahk_exe devenv.exe")
	g_1_ProgramGroups("VisualStudio_Schemas","Schemas ahk_exe devenv.exe")
	g_1_ProgramGroups("VisualStudio_WithAdministrator","(Administrator) ahk_group VisualStudio")
	g_1_ProgramGroups("VisualStudioSQL","bsSQL ahk_Group VisualStudio")
	g_1_ProgramGroups("VPNFailure","VPN Connection Failure ahk_class #32770 ahk_exe FortiTray.exe", "VPN connection failed.")
	g_1_ProgramGroups("VSCode","ahk_class Chrome_WidgetWin_1 ahk_exe VSCodium.exe")
	g_1_ProgramGroups("VSCode","Visual Studio Code ahk_class Chrome_WidgetWin_1 ahk_exe Code.exe")
	g_1_ProgramGroups("WinampMain","Winamp ahk_class Winamp v1.x")
	g_1_ProgramGroups("WinampSecondary","Winamp Library ahk_class Winamp Gen")
	g_1_ProgramGroups("WinampSecondary","Winamp Playlist Editor ahk_class Winamp PE")
	g_1_ProgramGroups("WindowsTaskManager","Task Manager ahk_exe taskmgr.exe")
	g_1_ProgramGroups("WindowsTaskManager","Windows Task Manager")
	g_1_ProgramGroups("Wisdominator","WisdominatorConsole.exe")
	g_1_ProgramGroups("XLite","X-Lite ahk_exe X-Lite.exe")
	g_1_ProgramGroups_End("AbortRecursiveDive","Attach to Process ahk_group VisualStudio")
	g_1_ProgramGroups_End("AbortRecursiveDive","File Modification Detected ahk_group VisualStudio")
	g_1_ProgramGroups_End("AbortRecursiveDive","Microsoft Visual Studio ahk_group VisualStudio","Save changes to the following item")
	g_1_ProgramGroups_End("AbortRecursiveDive","Microsoft Visual Studio ahk_group VisualStudio","This file has been modified outside of the source editor.")
	g_1_ProgramGroups_End("AbortRecursiveDive","QuickWatch ahk_group VisualStudio")
	g_1_ProgramGroups_End("AbortRecursiveDive","Text Visualizer ahk_group VisualStudio")
	g_1_ProgramGroups_End("AllMinorWindows","ahk_group MinorWindows")
	g_1_ProgramGroups_End("AllMinorWindows","ahk_group MinorWindowsLevel2")
	g_1_ProgramGroups_End("AllowControlTilde","ahk_group Browsers")
	g_1_ProgramGroups_End("AllowScrollLock","ahk_group Emacs")
	g_1_ProgramGroups_End("Chrome_Hiders","ahk_group Chrome_Wunderlist")
	g_1_ProgramGroups_End("Chrome_NoDevTools","ahk_group Chrome",,,"DevTools -")
	g_1_ProgramGroups_End("ChromeDevTools","Developer Tools ahk_group ChromiumBrowser")
	g_1_ProgramGroups_End("ChromeDevTools","DevTools ahk_group ChromiumBrowser")
	g_1_ProgramGroups_End("ChromiumBrowser","ahk_group Brave")
	g_1_ProgramGroups_End("ChromiumBrowser","ahk_group Chrome")
	g_1_ProgramGroups_End("ConEmu_PowerShell","PS (Admin) ahk_group ConEmu")
	g_1_ProgramGroups_End("ConnectWise","ConnectWise ahk_group Browsers")
	g_1_ProgramGroups_End("ControlWtoControlF4","ahk_group DataGrip")
	g_1_ProgramGroups_End("ControlWtoControlF4","ahk_group IntelliJIdea")
	g_1_ProgramGroups_End("ControlWtoControlF4","ahk_group PowershellISE")
	g_1_ProgramGroups_End("ControlWtoControlF4","ahk_group Rider")
	g_1_ProgramGroups_End("DevBuildSolution","DevBuildSolution ahk_group VisualStudio")
	g_1_ProgramGroups_End("DoNotGrowlCallStack","ahk_group SampleApp")
	g_1_ProgramGroups_End("DotnetIDE","ahk_group Rider")
	g_1_ProgramGroups_End("DotnetIDE","ahk_group VisualStudio")
	g_1_ProgramGroups_End("FirefoxDevTools", "Developer Tools ahk_group Firefox")
	g_1_ProgramGroups_End("GmailLoginScreen","Accounts ahk_class NUIDialog ahk_exe OUTLOOK.EXE")
	g_1_ProgramGroups_End("GmailLoginScreen","ahk_exe youtube-music-desktop-app.exe")
	g_1_ProgramGroups_End("GmailLoginScreen","ahk_group Rambox")
	g_1_ProgramGroups_End("GmailLoginScreen","ChatGPT ahk_class Window Class ahk_exe ChatGPT.exe")
	g_1_ProgramGroups_End("GmailLoginScreen","Gmail ahk_group Browsers")
	g_1_ProgramGroups_End("GmailLoginScreen","Google Calendar - Sign in ahk_group Browsers")
	g_1_ProgramGroups_End("GmailLoginScreen","Google Play ahk_group Browsers")
	g_1_ProgramGroups_End("GmailLoginScreen","Sign in - Google Accounts ahk_group Browsers")
	g_1_ProgramGroups_End("GmailLoginScreen","YouTube ahk_group Browsers")
	g_1_ProgramGroups_End("GmailLoginScreen","YouTube Music ahk_class Chrome_WidgetWin_1 ahk_exe YouTube Music.exe")
	g_1_ProgramGroups_End("GoogleSheets","Google Sheets ahk_group Browsers")
	g_1_ProgramGroups_End("LaterConsole","ahk_group LaterConsoleBeta")
	g_1_ProgramGroups_End("LaterConsole","ahk_group LaterConsoleProd")
	g_1_ProgramGroups_End("MicrosoftSignInWindow","Sign in to Minecraft ahk_class MCLWindow ahk_exe Minecraft.exe")
	g_1_ProgramGroups_End("MinorWindows","ahk_group JsonView")
	g_1_ProgramGroups_End("MinorWindows","ahk_group SourceGear")
	g_1_ProgramGroups_End("Outlook","ahk_exe Outlook.exe","","","ahk_group OutlookEmail") ;the exclude isn't working on 2-10-15
	g_1_ProgramGroups_End("PaulAtOtakuDB","paul@otakudb.com - Otakudb.com Mail ahk_group Browsers")
	g_1_ProgramGroups_End("PowerShellOrPWSH_Exe","ahk_exe powershell.exe") ;ok
	g_1_ProgramGroups_End("PowerShellOrPWSH_Exe","ahk_exe pwsh.exe")
	g_1_ProgramGroups_End("PowerShellWindow","ahk_group PowerShell")
	g_1_ProgramGroups_End("PowerShellWindow","ahk_group PowerShellCore")
	g_1_ProgramGroups_End("ProcessHacker","ahk_group SystemInformer")
	g_1_ProgramGroups_End("RotateBucket","ahk_group SQLManagementStudio")
	g_1_ProgramGroups_End("RotateBucket","ahk_group VisualStudio")
	g_1_ProgramGroups_End("Songza","Songza ahk_group Browsers")
	g_1_ProgramGroups_End("SQLEditor","ahk_group DataGrip")
	g_1_ProgramGroups_End("VisualStudio_Cricket","Cricket.Intranet ahk_group VisualStudio")
	g_1_ProgramGroups_End("WCRI_Page", "My Dashboard ahk_group browsers")
	g_1_ProgramGroups_End("WCRI_Page"," - WCRI ahk_group browsers")
	g_1_ProgramGroups_End("WCRI_SignIn","WCRI Login ahk_group browsers")
	g_1_ProgramGroups_End("WCRI_SignIn","WCRI Sign In ahk_group browsers")
	g_1_ProgramGroups_End("WCRISignin","WCRI Log In ahk_group Browsers")
	g_1_ProgramGroups_End("WCRISignin","WCRI Sign In ahk_group Browsers")
	g_1_ProgramGroups_End("WindowsTaskManager","ahk_group ProcessHacker")
	g_2_AutomaticBehaviors("ActivateAndAltF4IfExist","ahk_class #32770 ahk_exe MSACCESS.EXE","The changes you requested to the table were not successful because they would create duplicate values in the index, primary key, or relationship")
	g_2_AutomaticBehaviors("ActivateAndAltF4IfExist","Broadcast Request ahk_class #32770 ahk_exe tstbench.exe")
	g_2_AutomaticBehaviors("ActivateAndAltF4IfExist","Magnifier ahk_class Screen Magnifier Window ahk_exe Magnify.exe")
	g_2_AutomaticBehaviors("ActivateAndAltF4IfExist","Microsoft Visual Studio ahk_exe devenv.exe","JavaScript Memory Analysis is not supported on versions of Windows prior to Windows 8.")
	g_2_AutomaticBehaviors("ActivateAndAltF4IfExist","Server Notes.txt - Notepad ahk_class Notepad ahk_exe NOTEPAD.EXE")
	g_2_AutomaticBehaviors("ActivateAndAltF4IfExist","Starting the emulator.  Please be patient. ahk_class SunAwtDialog ahk_exe javaw.exe")
	g_2_AutomaticBehaviors("ActivateAndAltF4IfExist_Fast","ahk_class #32770 ahk_exe TortoiseGitMerge.exe","The diffing engine aborted because of an error")
	g_2_AutomaticBehaviors("ActivateAndAltF4IfExist_Fast","Edit and Continue ahk_group VisualStudio","Changes are not allowed in the following cases:")
	g_2_AutomaticBehaviors("ActivateAndAltF4IfExist_Fast","Edit and Continue ahk_group VisualStudio","Changes to 64-bit applications are not allowed.")
	g_2_AutomaticBehaviors("ActivateAndAltF4IfExist_Fast","Microsoft Outlook ahk_exe outlook.exe","It's possible the file is already open, or you don't have permission to open it.")
	g_2_AutomaticBehaviors("ActivateAndAltF4IfExist_Fast","Microsoft Visual Studio ahk_exe devenv.exe","The debugger cannot unwind to this frame.")
	g_2_AutomaticBehaviors("ActivateAndAltFIfExist","Performance Wizard -- Page 1 of 3 ahk_exe devenv.exe")
	g_2_AutomaticBehaviors("ActivateAndAltNIfExist","Microsoft Visual Studio ahk_class #32770 ahk_group VisualStudio","Microsoft Visual Studio has detected that an operation is blocking user input")
	g_2_AutomaticBehaviors("ActivateAndAltNIfExist","Microsoft Visual Studio ahk_class #32770 ahk_group VisualStudio","The source control provider associated with this solution could not be found")
	g_2_AutomaticBehaviors("ActivateAndAltYIfExist_Fast","Rename ahk_class #32770 ahk_exe Explorer.EXE","Yes")
	g_2_AutomaticBehaviors("ActivateAndEnter","Microsoft Office Outlook ahk_class #32770","Send the response now.")
	g_2_AutomaticBehaviors("ActivateAndEscapeIfExist","(PortableApps.com Launcher) ahk_class #32770","Portable did not close properly last time it was run")
	g_2_AutomaticBehaviors("ActivateAndEscapeIfExist","bsWFconversion ahk_class #32770 ahk_exe bsWFconversion.vshost.exe","Warning: Null value is eliminated by an aggregate or other SET operation.")
	g_2_AutomaticBehaviors("ActivateAndEscapeIfExist","Connect to Report Server ahk_exe MSReportBuilder.exe")
	g_2_AutomaticBehaviors("ActivateAndEscapeIfExist","GoToMeeting ahk_class #32770 ahk_exe g2mui.exe","The meeting has ended")
	g_2_AutomaticBehaviors("ActivateAndEscapeIfExist","Microsoft Office Outlook ahk_class #32770","Failed to update headers.")
	g_2_AutomaticBehaviors("ActivateAndEscapeIfExist","Microsoft Visual Studio ahk_group VisualStudio","One or more projects in the solution were not loaded correctly.")
	g_2_AutomaticBehaviors("ActivateAndEscapeIfExist","Microsoft Visual Studio ahk_group VisualStudio","Reason: File and project names cannot contain any of the following characters: /\?:&*")
	g_2_AutomaticBehaviors("ActivateAndEscapeIfExist","Microsoft Visual Studio Express 2012 for Web ahk_class #32770 ahk_exe VWDExpress.exe","Unable to start debugging on the web server. Remote debugging is not supported.")
	g_2_AutomaticBehaviors("ActivateAndEscapeIfExist","nul`, ahk_class #32770 ahk_exe sgdm.exe","OK")
	g_2_AutomaticBehaviors("ActivateAndEscapeIfExist","Source Control ahk_group VisualStudio","but its binding information cannot be found. Because it is not possible")
	g_2_AutomaticBehaviors("ActivateAndEscapeIfExist","Source Control ahk_group VisualStudio","The solution appears to be under source")
	g_2_AutomaticBehaviors("ActivateAndEscapeIfExist","SourceGear Vault Standard ahk_class #32770 ahk_exe VaultGUIClient.exe","Session is no longer valid.  Either the server restarted")
	g_2_AutomaticBehaviors("ActivateAndEscapeIfExist","SourceGear Vault Windows Client ahk_class #32770 ahk_exe dw20.exe","Check online for a solution and close the program")
	g_2_AutomaticBehaviors("ActivateAndEscapeIfExist","Toolbar ahk_class #32770 ahk_exe AutoHotkey.exe","Error trying to get the director interface!")
	g_2_AutomaticBehaviors("ActivateAndEscapeIfExist_Fast","Edit and Continue ahk_group VisualStudio","Changes are not allowed while code is running.")
	g_2_AutomaticBehaviors("ActivateAndEscapeIfExist_Fast","TstBench Window ahk_class #32770","Creating the Java VM required for the communications failed, please make sure that a JAVA JRE is installed and selected correctly or that the KmCache loaded")
	g_2_AutomaticBehaviors("ActivateAndEscapeIfExist_Fast","TstBench Window ahk_class #32770","Error loading java library with code 126")
	g_2_AutomaticBehaviors("ActivateIfExist","ahk_group ActivateAndEscapeIfExist")
	g_2_AutomaticBehaviors("ActivateIfExist","ahk_group VPNFailure")
	g_2_AutomaticBehaviors("ActivateIfExist","AHKCOMMAND:")
	g_2_AutomaticBehaviors("ActivateIfExist_Fast","Inconsistent Line Endings ahk_class #32770 ahk_exe Ssms.exe")
	g_2_AutomaticBehaviors("ActivateIfExist_Fast","Keep non existing file ahk_class #32770 ahk_exe notepad++.exe")
	g_2_AutomaticBehaviors("ActivateIfExist_Slow","Microsoft Visual Studio ahk_class #32770 ahk_exe devenv.exe","The active solution or project is controlled by a different source control plug-in than the one you have selected")
	g_2_AutomaticBehaviors("ActivateIfExist_Slow","Microsoft Visual Studio ahk_class #32770 ahk_exe devenv.exe","Would you like to build it?")
	g_2_AutomaticBehaviors("ActivateIfExist_Slow","Microsoft Visual Studio ahk_class #32770 ahk_exe dwwin.exe","Check online for a solution and restart the program")
	g_2_AutomaticBehaviors("ActivateIfExist_Slow","Microsoft Visual Studio Express 2012 for Web ahk_class #32770 ahk_exe VWDExpress.exe","Would you like to contact this server to try to enable source control integration?")
	g_2_AutomaticBehaviors("ActivateIfExist_Slow","Spelling: ahk_class bosa_sdm_msword ahk_exe WINWORD.EXE")
	g_2_AutomaticBehaviors("ActivateIfExist_Slow","VPN Client  |  User Authentication for ahk_class QWidget ahk_exe vpngui.exe")
	g_2_AutomaticBehaviors("ActivateIfExist_Slow","WindowTitleMonitor ahk_class #32770 ahk_exe AutoHotkey.exe", "Could not close the previous instance of this script")
	g_2_AutomaticBehaviors("AltAifActive","ahk_exe ssms.exe","New version is available!")
	g_2_AutomaticBehaviors("AltAifActive","Attach Security Warning ahk_group VisualStudio","Attaching to this process can potentially harm your computer. If the information below looks suspicious or you are unsure, do not attach to this process.")
	g_2_AutomaticBehaviors("AltAifActive","Attach Security Warning ahk_group VisualStudio","w3wp.exe")
	g_2_AutomaticBehaviors("AltAifActive","KeePassHttp: Confirm Access ahk_exe KeePass.exe")
	g_2_AutomaticBehaviors("AltDifActive","Session Manager - Restore after Crash ahk_class MozillaDialogClass")
	g_2_AutomaticBehaviors("AltF4IfActive","Comment ahk_class #32770 ahk_exe TeamViewer.exe")
	g_2_AutomaticBehaviors("AltF4IfActive","dbForge SQL Complete","Login failed for user")
	g_2_AutomaticBehaviors("AltF4IfActive","Microsoft Visual Studio ahk_class #32770 ahk_exe devenv.exe","Error: The data necessary to complete this operation is not yet available")
	g_2_AutomaticBehaviors("AltF4IfActive","Microsoft Visual Studio ahk_class #32770 ahk_exe dwwin.exe","Check online for a solution and restart the program")
	g_2_AutomaticBehaviors("AltF4IfActive","Session Timeout - Walgreens")
	g_2_AutomaticBehaviors("AltF4IfActive","SourceGear Vault Standard Error ahk_exe VaultGUIClient.exe","Session is no longer valid.")
	g_2_AutomaticBehaviors("AltF4IfActive","SourceGear Vault Standard Error","The username or password supplied is invalid.")
	g_2_AutomaticBehaviors("AltNifActive","adp ahk_class #32770","You copied a large amount of data onto the Clipboard.")
	g_2_AutomaticBehaviors("AltNifActive","Microsoft Access ahk_class #32770","Would you like to remove the compacted database from Source Code Control?")
	g_2_AutomaticBehaviors("AltNifActive","Microsoft Visual Basic 2010 Express ahk_class #32770","The source control provider associated with this solution could not be found. The projects will be treated as not under source control.")
	g_2_AutomaticBehaviors("AltNifActive","Microsoft Visual Studio ahk_group VisualStudio","The active solution or project is controlled by a different source control plug-in than the one you have selected")
	g_2_AutomaticBehaviors("AltNifActive","Microsoft Visual Studio Express 2012 for Web ahk_class #32770 ahk_exe VWDExpress.exe","Would you like to contact this server to try to enable source control integration?")
	g_2_AutomaticBehaviors("AltNIfActive_Slow","WindowTitleMonitor ahk_class #32770 ahk_exe AutoHotkey.exe", "Could not close the previous instance of this script")
	g_2_AutomaticBehaviors("AltNplusHeadshotifActive","ahk_class #32770","Do you want to save changes to the design of table")
	g_2_AutomaticBehaviors("AltNplusHeadshotifActive","ahk_class #32770","Do you want to save changes to the design of view")
	g_2_AutomaticBehaviors("AltNplusHeadshotifActive","ahk_class #32770","Do you want to save changes to the layout of table")
	g_2_AutomaticBehaviors("AltYifActive","Microsoft Access ahk_class #32770","mde already exists. Do you want to replace the existing file?")
	g_2_AutomaticBehaviors("AltYifActive","Microsoft Access ahk_class #32770","Microsoft Access must close the form")
	g_2_AutomaticBehaviors("AltYifActive","Microsoft Access ahk_class #32770","Microsoft Access must close the query")
	g_2_AutomaticBehaviors("AltYifActive","Microsoft Excel ahk_class #32770 ahk_exe EXCEL.EXE","Some features in your workbook might be lost if you save it as CSV (Comma delimited)")
	g_2_AutomaticBehaviors("AltYifActive","Microsoft Excel ahk_class #32770","may contain features that are not compatible with CSV (Comma delimited).  Do you want to keep the workbook in this format?")
	g_2_AutomaticBehaviors("AltYifActive","Microsoft Excel ahk_class #32770","may contain features that are not compatible with Text (Tab delimited).  Do you want to keep the workbook in this format?")
	g_2_AutomaticBehaviors("AltYifActive","Microsoft Office Access ahk_class #32770","Microsoft Office Access must close the")
	g_2_AutomaticBehaviors("AltYifActive","Microsoft Office Outlook ahk_class #32770","An attachment to this message may be currently open in another program. If you continue")
	g_2_AutomaticBehaviors("AltYifActive","Microsoft SQL Server Management Studio","This database does not have one or more of the support objects required to use database diagramming.")
	g_2_AutomaticBehaviors("AltYifActive","Microsoft Visual Studio ahk_group VisualStudio","This command compares the disk version of a file to the server version")
	g_2_AutomaticBehaviors("AltYIfActive","PowerGUI Script Editor ahk_class #32770 ahk_exe ScriptEditor.exe","has been changed outside PowerGUI Script Editor")
	g_2_AutomaticBehaviors("AltYifActive","Source Code Control ahk_class #32770","If you do not check it out")
	g_2_AutomaticBehaviors("AltYifActive_Fast","Confirm ahk_class TBcMessageForm.UnicodeClass ahk_exe BCompare.exe")
	g_2_AutomaticBehaviors("AltYifActive_Fast","Keep non existing file ahk_class #32770 ahk_exe notepad++.exe")
	g_2_AutomaticBehaviors("AltYplusHeadshotifActive","Confirm Exit - GoToMeeting ahk_class #32770")
	g_2_AutomaticBehaviors("AutoSSMSsaverGroup","Microsoft SQL Server Management Studio ahk_class #32770 ahk_exe Ssms.exe","Save changes to the following items?")
	g_2_AutomaticBehaviors("CloseIfExist","ahk_exe powershell_ise.exe","The most recent Windows PowerShell ISE session did not")
	g_2_AutomaticBehaviors("CloseIfExist","ahk_group VisualStudio","An operation was attempted on a nonexistent network connection")
	g_2_AutomaticBehaviors("CloseIfExist","DiffMerge Error ahk_class #32770 ahk_exe sgdm.exe")
	g_2_AutomaticBehaviors("CloseIfExist","Feedback Hub ahk_class ApplicationFrameWindow ahk_exe ApplicationFrameHost.exe")
	g_2_AutomaticBehaviors("CloseIfExist","Office ahk_class ApplicationFrameWindow ahk_exe ApplicationFrameHost.exe")
	g_2_AutomaticBehaviors("CloseIfExist","Restore pages ahk_class Chrome_WidgetWin_1")
	g_2_AutomaticBehaviors("CloseIfExist","Restore pages ahk_class Chrome_WidgetWin_2")
	g_2_AutomaticBehaviors("CloseIfExist","Restore pages? ahk_class Chrome_WidgetWin_1")
	g_2_AutomaticBehaviors("CloseIfExist","TeamViewer ahk_class CreativeView ahk_exe TeamViewer.exe")
	g_2_AutomaticBehaviors("CloseIfExist","TeamViewer ahk_class H-SMILE-FRAME ahk_exe TeamViewer.exe")
	g_2_AutomaticBehaviors("CloseIfExist","Untitled ahk_class Chrome_WidgetWin_1 ahk_exe slack.exe")
	g_2_AutomaticBehaviors("EnterIfActive","Error ahk_class #32770","One or more keyboard shortcuts for Inspect may not work since another application is already using them.") ;Inspect.exe
	g_2_AutomaticBehaviors("EnterIfActive","Gateway ahk_class #32770 ahk_exe SampleUtilityApplication.exe","The DC has been updated")
	g_2_AutomaticBehaviors("EnterIfActive","Internet Explorer ahk_class #32770 ahk_exe IEXPLORE.EXE","Are you sure you want to navigate away from this page?")
	g_2_AutomaticBehaviors("EnterIfActive","Message from webpage ahk_class #32770 ahk_exe IEXPLORE.EXE","THIS CREDIT APPLICATION IS FOR TRADITIONAL TRACTOR LEASES ONLY (NOT PREVIOUSLY FLEET OWNED EQUIPMENT)")
	g_2_AutomaticBehaviors("EnterIfActive","Microsoft Excel ahk_class #32770","The selected file type does not support workbooks that contain multiple sheets")
	g_2_AutomaticBehaviors("EnterIfActive","Microsoft Office Access","This version of Microsoft Office Access")
	g_2_AutomaticBehaviors("EnterIfActive","Remote Desktop Connection ahk_class #32770","This will disconnect your Remote Desktop Services session.")
	g_2_AutomaticBehaviors("EnterIfActive","SourceGear Vault Standard ahk_class #32770","Warning: Your license will expire within")
	g_2_AutomaticBehaviors("EnterIfActive","TortoiseGitMerge ahk_class #32770 ahk_exe TortoiseGitMerge.exe", "The text is identical, but the files do")
	g_2_AutomaticBehaviors("EnterIfActive","VMRC Negotiate Authentication ahk_class #32770")
	g_2_AutomaticBehaviors("EnterIfActive_Fast","Open Executable File? ahk_class MozillaDialogClass")
	g_2_AutomaticBehaviors("EnterPlusHeadshotIfActive","Disconnect Terminal Services Session ahk_class #32770")
	g_2_AutomaticBehaviors("EnterPlusHeadshotIfActive","Disconnect Windows session ahk_class #32770")
	g_2_AutomaticBehaviors("EscapeIfActive","ahk_group ActivateAndEscapeIfExist")
	g_2_AutomaticBehaviors("EscapeIfActive","Call Quality Feedback ahk_class TskCallQualityForm.UnicodeClass")
	g_2_AutomaticBehaviors("EscapeIfActive","DirectSound output v2.47 (d) error ahk_class #32770")
	g_2_AutomaticBehaviors("EscapeIfActive","Export - PDF ahk_class NUIDialog")
	g_2_AutomaticBehaviors("EscapeIfActive","Nullsoft DirectSound Output  ahk_class #32770")
	g_2_AutomaticBehaviors("EscapeIfActive","Remote Desktop Connection ahk_class #32770","connect to the remote computer for one of these reasons")
	g_2_AutomaticBehaviors("EscapeIfActive","Remote Desktop Connection ahk_class #32770","Remote Desktop can't connect to the remote computer")
	g_2_AutomaticBehaviors("EscapeIfActive","Remote Desktop Connection ahk_class #32770","Remote Desktop can't find the computer")
	g_2_AutomaticBehaviors("EscapeIfActive","Remote Desktop Connection ahk_class #32770","Your Remote Desktop session has ended.")
	g_2_AutomaticBehaviors("EscapeIfActive","Task Scheduler ahk_class #32770","An error has occurred for task Reminders")
	g_2_AutomaticBehaviors("EscapeIfActive","Terminal Services Manager ahk_class #32770","Access is denied")
	g_2_AutomaticBehaviors("EscapeIfActive","XML Tools plugin ahk_class #32770 ahk_exe notepad++.exe","Errors detected in content. Please correct them before applying pretty print.")
	g_2_AutomaticBehaviors("EscapePlusHeadshotIfActive","Microsoft Office Outlook ahk_class #32770","Your IMAP server has closed the connection. This may occur if you have left the connection idle for too long.")
	g_2_AutomaticBehaviors("EscapePlusHeadshotIfActive","Remote Desktop Connection ahk_class #32770","Another user connected to the remote computer")
	g_2_AutomaticBehaviors("EscapePlusHeadshotIfActive","Remote Desktop Connection ahk_class #32770","connect to the remote computer for one of these reasons")
	g_2_AutomaticBehaviors("EscapeToAltN","Microsoft Visual Studio ahk_group VisualStudio","Do you want to configure this solution to download and restore missing NuGet packages during build")
	g_2_AutomaticBehaviors("GMail_BSI","paul@bsifargo.com - Business Software")
	g_2_AutomaticBehaviors("HideIfExist","ahk_class VisualStudioGlowWindow ahk_exe devenv.exe")
	g_2_AutomaticBehaviors("HideIfExist","CiceroUIWndFrame ahk_class CiceroUIWndFrame ahk_exe devenv.exe")
	g_2_AutomaticBehaviors("HideIfExist","PopupMessageWindow ahk_class SunAwtFrame ahk_exe datagrip64.exe")
	g_2_AutomaticBehaviors("HideIfExist","PopupMessageWindow ahk_class SunAwtFrame ahk_exe rider64.exe")
	g_2_AutomaticBehaviors("HideIfExist","theAwtToolkitWindow ahk_class SunAwtToolkit ahk_exe datagrip64.exe")
	g_2_AutomaticBehaviors("HideIfExist","Visual Studio Application Management Window ahk_class VisualStudioAppManagement ahk_exe devenv.exe")
	g_2_AutomaticBehaviors("MaximizeRightIfNew","Adobe Reader ahk_class AcrobatSDIWindow")
	g_2_AutomaticBehaviors("MaximizeRightIfNew","ahk_class AcrobatSDIWindow ahk_exe AcroRd32.exe")
	g_2_AutomaticBehaviors("MaxToWindow","ahk_group Browsers")
	g_2_AutomaticBehaviors("MButton","ahk_exe BattleBit.exe")
	g_2_AutomaticBehaviors("MButton","ahk_group Emacs")
	g_2_AutomaticBehaviors("MButton","ahk_group Krita")
	g_2_AutomaticBehaviors("MButton","ahk_group Minecraft")
	g_2_AutomaticBehaviors("NeverStraddle","ahk_class #32770")
	g_2_AutomaticBehaviors("NeverStraddle","Notepad ahk_class Notepad ahk_exe notepad.exe")
	g_2_AutomaticBehaviors("NoMax","ahk_class OpenShell.CMenuContainer ahk_exe Explorer.EXE")
	g_2_AutomaticBehaviors("NoMax","ahk_exe calc.exe")
	g_2_AutomaticBehaviors("NoMax","ahk_exe SampleUtilityApplication.exe")
	g_2_AutomaticBehaviors("NoMax","Connect to Server ahk_exe Ssms.exe","Re&member password")
	g_2_AutomaticBehaviors("NoMax","Find ahk_class #32770 ahk_exe AbiWord.exe")
	g_2_AutomaticBehaviors("NoMax","Run ahk_class #32770 ahk_exe explorer.exe")
	g_2_AutomaticBehaviors("NoMax","Windows Security ahk_class #32770")
	g_2_ProgramGroups_End("ActiveFile","ahk_group AHKtextEditor")
	g_2_ProgramGroups_End("ActiveFile","ahk_group Emacs")
	g_2_ProgramGroups_End("ActiveFile","ahk_group Everything")
	g_2_ProgramGroups_End("ActiveFile","ahk_group Obsidian")
	g_2_ProgramGroups_End("ActiveFile","ahk_group VisualStudio")
	g_2_ProgramGroups_End("ActiveFile","ahk_group VSCode")
	g_2_ProgramGroups_End("ActiveFile","ahk_group VSCodium")
	g_2_ProgramGroups_End("DeployCricketAll","PS: Deploy ahk_class ConsoleWindowClass ahk_group PowerShellWindow")
	g_2_ProgramGroups_End("DeployCricketAlpha","PS: Deploy Alpha ahk_class ConsoleWindowClass ahk_group PowerShellWindow")
	g_2_ProgramGroups_End("DeployCricketBeta","PS: Deploy Beta ahk_class ConsoleWindowClass ahk_group PowerShellWindow")
	g_2_ProgramGroups_End("DeployCricketGamma","PS: Deploy Gamma ahk_class ConsoleWindowClass ahk_group PowerShellWindow")
	g_2_ProgramGroups_End("DeployCricketProd","PS: Deploy Prod ahk_class ConsoleWindowClass ahk_group PowerShellWindow")
	g_2_ProgramGroups_End("DeployCricketTest","PS: Deploy Test ahk_class ConsoleWindowClass ahk_group PowerShellWindow")
	g_2_ProgramGroups_End("MinToBack","ahk_group Browsers")
	g_2_ProgramGroups_End("PowerShellAll","ahk_class ConsoleWindowClass ahk_group PowerShellWindow")
	g_2_ProgramGroups_End("TextEditor","ahk_group AHKTextEditor")
	g_2_ProgramGroups_End("TextEditor","ahk_group DataGrip")
	g_2_ProgramGroups_End("TextEditor","ahk_group DotnetIDE")
	g_2_ProgramGroups_End("TextEditor","ahk_group Rider")
	g_2_ProgramGroups_End("TextEditor","ahk_group VisualStudio")
	g_2_ProgramGroups_End("TextEditor","ahk_group VSCode")
	g_2_ProgramGroups_End("vsHide","ahk_group CyberSentryComputerReadout")
	g_2_ProgramGroups_End("vsHide","ahk_group VSCode")
	g_2_ProgramGroups_End("WatchCricketAlpha","PS: Cricket Watch Alpha ahk_class ConsoleWindowClass ahk_group PowerShellWindow")
	g_2_ProgramGroups_End("WatchCricketBeta","PS: Cricket Watch Beta ahk_class ConsoleWindowClass ahk_group PowerShellWindow")
	g_2_ProgramGroups_End("WatchCricketGamma","PS: Cricket Watch Gamma ahk_class ConsoleWindowClass ahk_group PowerShellWindow")
	g_2_ProgramGroups_End("WatchCricketProd","PS: Cricket Watch Prod ahk_class ConsoleWindowClass ahk_group PowerShellWindow")
	g_2_ProgramGroups_End("WatchCricketTest","PS: Cricket Watch Test ahk_class ConsoleWindowClass ahk_group PowerShellWindow")
	g_3_OneOffProgramGroups("OneOff_StupidSecurityWarning","Open File - Security Warning ahk_class #32770","The publisher could not be verified.  Are you sure you want to run this software?")
	g_4_KeyBehaviors("AltControlF4Kill","ahk_group NPP")
	g_4_KeyBehaviors("AltUpDown","ahk_group SciTE")
	g_4_KeyBehaviors("BasicMiddleClick","ahk_exe bmgame.exe")
	g_4_KeyBehaviors("BasicMiddleClick","ahk_exe bmstartapp.exe")
	g_4_KeyBehaviors("BasicMiddleClick","ahk_exe NewColossus_x64vk.exe")
	g_4_KeyBehaviors("BasicMiddleClick","ahk_group RemoteDesktop")
	g_4_KeyBehaviors("BasicMiddleClick","BATMAN: ARKHAM")
	g_4_KeyBehaviors("BasicMiddleClick","ahk_exe DeadIsland-Win64-Shipping.exe")
	g_4_KeyBehaviors("BasicMiddleClick","Dead Island")
	g_4_KeyBehaviors("ControlQtoAltF4","ahk_exe paintdotnet.exe")
	g_4_KeyBehaviors("ControlQtoAltF4","ahk_group VSCode")
	g_4_KeyBehaviors("ControlQtoAltF4","Picker ahk_exe MatrixNexus.exe")
	g_4_KeyBehaviors("ControlQtoAltF4","Picker ahk_exe MatrixOS.exe")
	g_4_KeyBehaviors("ControlWtoAltF4","ahk_class ApplicationFrameWindow ahk_exe ApplicationFrameHost.exe")
	g_4_KeyBehaviors("ControlWtoAltF4","ahk_class MSPaintApp ahk_exe mspaint.exe")
	g_4_KeyBehaviors("ControlWtoAltF4","ahk_class OEcl ahk_exe MSACCESS.EXE") ;field Selector
	g_4_KeyBehaviors("ControlWtoAltF4","ahk_class rctrl_renwnd32") ;Outlook Email
	g_4_KeyBehaviors("ControlWtoAltF4","ahk_group Clipmaster_SQL_Report")
	g_4_KeyBehaviors("ControlWtoAltF4","ahk_group JsonView")
	g_4_KeyBehaviors("ControlWtoAltF4","File Download ahk_class #32770")
	g_4_KeyBehaviors("ControlWtoAltF4","Find in All Tabs ahk_exe firefox.exe")
	g_4_KeyBehaviors("ControlWtoAltF4","Picker ahk_exe MatrixNexus.exe")
	g_4_KeyBehaviors("ControlWtoAltF4","Picker ahk_exe MatrixOS.exe")
	g_4_KeyBehaviors("ControlWtoAltF4","Query Designer")
	g_4_KeyBehaviors("ControlWtoAltN","ahk_class #32770 ahk_exe MSACCESS.EXE","Do you want to save changes to the design of")
	g_4_KeyBehaviors("ControlWtoAltN","ahk_class #32770","Do you want to save the changes made to the SQL statement and update the property?")
	g_4_KeyBehaviors("ControlWtoAltN","LINQPad ahk_class #32770 ahk_group LINQPad","Save Query")
	g_4_KeyBehaviors("ControlWtoAltN","Microsoft Access ahk_class #32770","Do you want to save changes to the design of")
	g_4_KeyBehaviors("ControlWtoAltN","Microsoft Excel ahk_class NUIDialog ahk_exe EXCEL.EXE")
	g_4_KeyBehaviors("ControlWtoAltN","Microsoft Office Access  ahk_class #32770","Do you want to save changes to the design of")
	g_4_KeyBehaviors("ControlWtoAltN","Microsoft Office Access  ahk_class #32770","Do you want to save the changes made to the query and update the property?")
	g_4_KeyBehaviors("ControlWtoAltN","Microsoft Office Outlook ahk_class #32770","Do you want to save changes?")
	g_4_KeyBehaviors("ControlWtoAltN","Microsoft SQL Server Management Studio ahk_class #32770","Save changes to the following items")
	g_4_KeyBehaviors("ControlWtoAltN","Microsoft Visual Studio ahk_class #32770","Save changes to the following items")
	g_4_KeyBehaviors("ControlWtoAltN","Microsoft Visual Studio ahk_group VisualStudio","Save changes to the following items")
	g_4_KeyBehaviors("ControlWtoAltN","Microsoft Word ahk_class NUIDialog ahk_exe WINWORD.EXE")
	g_4_KeyBehaviors("ControlWtoAltN","Notepad ahk_class #32770")
	g_4_KeyBehaviors("ControlWtoAltN","PowerGUI Script Editor ahk_class #32770","was modified. Save changes?")
	g_4_KeyBehaviors("ControlWtoAltN","Save ahk_class #32770",,,"Save modified files?")
	g_4_KeyBehaviors("ControlWtoAltN","SciTE ahk_class #32770")
	g_4_KeyBehaviors("ControlWtoAltN","Unsaved Changes ahk_exe paintdotnet.exe")
	g_4_KeyBehaviors("ControlWtoAltN","Windows PowerShell ISE - Warning ahk_class #32770 ahk_exe powershell_ise.exe")
	g_4_KeyBehaviors("ControlWtoControlF4","ahk_class SunAwtFrame ahk_exe webstorm64.exe")
	g_4_KeyBehaviors("ControlWtoControlF4","ahk_exe webstorm64.exe")
	g_4_KeyBehaviors("ControlWtoControlF4","Windows PowerShell ISE ahk_exe powershell_ise.exe")
	g_4_KeyBehaviors("DefaultFileOpener","ahk_class CabinetWClass")
	g_4_KeyBehaviors("DefaultFileOpener","ahk_class ExploreWClass")
	g_4_KeyBehaviors("DefaultFileOpener","ahk_class WorkerW")
	g_4_KeyBehaviors("DefaultFileOpener","ahk_exe AgentRansack.exe")
	g_4_KeyBehaviors("DefaultFileOpener","ahk_exe Q-Dir_x64.exe")
	g_4_KeyBehaviors("DefaultFileOpener","ahk_group Everything")
	g_4_KeyBehaviors("DefaultFileOpener","ExplorerXP ahk_class ExplorerXP Class")
	g_4_KeyBehaviors("DefaultFileOpener","Locate ahk_class #32770 ahk_exe locate32.exe")
	g_4_KeyBehaviors("DefaultFileOpener","Program Manager ahk_class Progman")
	g_4_KeyBehaviors("DoubleEscapeToClose","Source of: ahk_class MozillaWindowClass")
	g_4_KeyBehaviors("DoubleEscapeToHide","Terminal server connection - Windows Internet Explorer ahk_class IEFrame ahk_exe iexplore.exe")
	g_4_KeyBehaviors("DoubleEscapeToMinimize","KeePass ahk_exe KeePass.exe")
	g_4_KeyBehaviors("EscapeToClose","Active Window Info ahk_exe AU3_Spy.exe")
	g_4_KeyBehaviors("EscapeToClose","ahk_class MozillaWindowClass ahk_exe thunderbird.exe")
	g_4_KeyBehaviors("EscapeToClose","History Explorer")
	g_4_KeyBehaviors("EscapeToClose","FortiToken Windows ahk_class ApplicationFrameWindow ahk_exe ApplicationFrameHost.exe") ;work
	g_4_KeyBehaviors("EscapeToClose","Please Register ahk_class wxWindowNR ahk_exe sgdm.exe")
	g_4_KeyBehaviors("EscapeToClose","Query Designer")
	g_4_KeyBehaviors("EscapeToClose","Registration Information ahk_class wxWindowNR ahk_exe sgdm.exe")
	g_4_KeyBehaviors("EscapeToClose","Version Details ahk_exe VaultGUIClient.exe")
	g_4_KeyBehaviors("EscapeToHide","smtp4dev ahk_exe smtp4dev.exe")
	g_4_KeyBehaviors("EscapeToMinimize","ahk_class MainWindowClassName ahk_exe ProcessHacker.exe")
	g_4_KeyBehaviors("F12HideWindow","ahk_class #32770 ahk_exe locate32.exe")
	g_4_KeyBehaviors("F12HideWindow","ahk_class Chrome_WidgetWin_1 ahk_exe Chrome.exe",,,"Chrome App Launcher")
	g_4_KeyBehaviors("F12HideWindow","ahk_class ConsoleWindowClass ahk_exe sh.exe") ;GIT BASH
	g_4_KeyBehaviors("F12HideWindow","ahk_class ConsoleWindowClass ahk_exe WisdominatorConsole.exe")
	g_4_KeyBehaviors("F12HideWindow","ahk_class ProcessHacker ahk_exe ProcessHacker.exe")
	g_4_KeyBehaviors("F12HideWindow","ahk_exe 7+ Taskbar Tweaker.exe")
	g_4_KeyBehaviors("F12HideWindow","ahk_exe ets.exe")
	g_4_KeyBehaviors("F12HideWindow","ahk_exe FSSConsole.exe")
	g_4_KeyBehaviors("F12HideWindow","ahk_exe MatrixNexus.exe")
	g_4_KeyBehaviors("F12HideWindow","ahk_exe MatrixOS.exe")
	g_4_KeyBehaviors("F12HideWindow","ahk_exe Obsidian.exe")
	g_4_KeyBehaviors("F12HideWindow","ahk_group ChaosControl")
	g_4_KeyBehaviors("F12HideWindow","ahk_group Chrome_ConnectWise")
	g_4_KeyBehaviors("F12HideWindow","ahk_Group Chrome_Hiders")
	g_4_KeyBehaviors("F12HideWindow","ahk_group LaterConsoleBeta")
	g_4_KeyBehaviors("F12HideWindow","ahk_group LaterConsoleProd")
	g_4_KeyBehaviors("F12HideWindow","ahk_group LuaMacros")
	g_4_KeyBehaviors("F12HideWindow","ahk_group LuaMacrosEditor")
	g_4_KeyBehaviors("F12HideWindow","ahk_group MatrixOS")
	g_4_KeyBehaviors("F12HideWindow","ahk_group MinecraftServer")
	g_4_KeyBehaviors("F12HideWindow","ahk_group PaulAtOtakuDB")
	g_4_KeyBehaviors("F12HideWindow","ahk_group PlanDoc")
	g_4_KeyBehaviors("F12HideWindow","ahk_group PowerGUI")
	g_4_KeyBehaviors("F12HideWindow","ahk_group PowerShellAll")
	g_4_KeyBehaviors("F12HideWindow","ahk_group SampleApp")
	g_4_KeyBehaviors("F12HideWindow","ahk_Group SQLManagementStudio")
	g_4_KeyBehaviors("F12HideWindow","ahk_group XLite")
	g_4_KeyBehaviors("F12HideWindow","AutoHotkey Help ahk_class HH Parent ahk_exe hh.exe")
	g_4_KeyBehaviors("F12HideWindow","AutoTogglConsole.exe ahk_class ConsoleWindowClass ahk_exe AutoTogglConsole.exe")
	g_4_KeyBehaviors("F12HideWindow","FileZilla ahk_class wxWindowNR ahk_exe FileZilla.exe")
	g_4_KeyBehaviors("F12HideWindow","FortiClient ahk_exe FortiClient.exe")
	g_4_KeyBehaviors("F12HideWindow","KeePass ahk_exe KeePass.exe")
	g_4_KeyBehaviors("F12HideWindow","Outlook Web App ahk_group Browsers")
	g_4_KeyBehaviors("F12HideWindow","PortableApps.com ahk_class TfrmMenu ahk_exe PortableAppsPlatform.exe")
	g_4_KeyBehaviors("F12HideWindow","projects.drawio ahk_exe atom.exe")
	g_4_KeyBehaviors("F12HideWindow","PS: BackgroundPowerShell ahk_group PowerShellOrPWSH_Exe")
	g_4_KeyBehaviors("F12HideWindow","Registry Editor ahk_class RegEdit_RegEdit")
	g_4_KeyBehaviors("F12HideWindow","Remote Desktop Connection Manager v2.2 ahk_exe RDCMan.exe")
	g_4_KeyBehaviors("F12HideWindow","Services (Local) ahk_class MMCMainFrame ahk_exe mmc.exe")
	g_4_KeyBehaviors("F12HideWindow","smtp4dev ahk_exe smtp4dev.exe")
	g_4_KeyBehaviors("F12HideWindow","TeamViewer ahk_class #32770 ahk_exe TeamViewer.exe")
	g_4_KeyBehaviors("F12HideWindow","TeamViewer ahk_class TV_ChatWindow ahk_exe TeamViewer.exe")
	g_4_KeyBehaviors("F12HideWindow","WinEventHub ahk_class MozillaWinEventHubClass ahk_exe firefox.exe")
	g_4_KeyBehaviors("F12HideWindow","Winperio ahk_class AutoHotkeyGUI")
	g_4_KeyBehaviors("F12MinimizeWindow","ahk_group Slack")
	g_4_KeyBehaviors("F12MinimizeWindow","ahk_group Spotify")
	g_4_KeyBehaviors("F1HideWindow","ahk_class Chrome_WidgetWin_1 ahk_exe Chrome.exe",,,"Chrome App Launcher")
	g_4_KeyBehaviors("F1HideWindow","ahk_class SQLManagementStudio")
	g_4_KeyBehaviors("F1HideWindow","ahk_group DocFetcher")
	g_4_KeyBehaviors("F1HideWindow","ahk_group LaterConsoleBeta")
	g_4_KeyBehaviors("F1HideWindow","ahk_group LuaMacrosEditor")
	g_4_KeyBehaviors("F1HideWindow","KeePass ahk_exe KeePass.exe")
	g_4_KeyBehaviors("F1ToMaximize","ahk_class rctrl_renwnd32 ahk_exe OUTLOOK.EXE")
	g_4_KeyBehaviors("F1ToMaximize","ANTS Performance Profiler 6.3 Professional")
	g_4_KeyBehaviors("F1ToMaximize","Internet Explorer ahk_class IEFrame")
	g_4_KeyBehaviors("F1ToMaximize","Outlook ahk_class rctrl_renwnd32")
	g_4_KeyBehaviors("F1ToMaximize","Queued`","brought to you by SitePen`")
	g_4_KeyBehaviors("F1ToMaximize","SourceGear Vault Standard")
	g_4_KeyBehaviors("FileSaveDialog","Enter name of file to save ahk_class #32770 ahk_exe firefox.exe")
	g_4_KeyBehaviors("FixControlBackspace","ahk_exe EXCEL.EXE")
	g_4_KeyBehaviors("FixControlBackspace","ahk_exe ONENOTE.EXE")
	g_4_KeyBehaviors("FixControlBackspace","ahk_exe OUTLOOK.EXE")
	g_4_KeyBehaviors("FixControlBackspace","ahk_exe soffice.bin")
	g_4_KeyBehaviors("FixControlBackspace","ahk_exe WINWORD.EXE")
	g_4_KeyBehaviors("FixSpacebar","Outlook ahk_class #32770 ahk_exe OUTLOOK.EXE")
	g_4_KeyBehaviors("NoControlShiftI","ahk_group Obsidian")
	g_4_KeyBehaviors("NoControlShiftI","ahk_group VisualStudio")
	g_4_KeyBehaviors("OperableText","ahk_class Chrome_WidgetWin_1 ahk_exe VSCodium.exe")
	g_4_KeyBehaviors("OperableText","ahk_class Emacs ahk_exe emacs.exe")
	g_4_KeyBehaviors("OperableText","ahk_exe VSCodium.exe")
	g_4_KeyBehaviors("OperableText","ahk_group AHKTextEditor")
	g_4_KeyBehaviors("OperableText","ahk_group DataGrip")
	g_4_KeyBehaviors("OperableText","ahk_group DotnetIDE")
	g_4_KeyBehaviors("OperableText","ahk_group Emacs")
	g_4_KeyBehaviors("OperableText","ahk_group VSCode")
	g_4_KeyBehaviors("Shifted","ahk_class VirtualConsoleClass ahk_exe ConEmu64.exe")
	g_4_KeyBehaviors("Shifted","ahk_group TextEditor")
	g_4_KeyBehaviors("SQLEditor","ahk_group SQLManagementStudio")
	g_4_KeyBehaviors("TopsArrowKeys","ahk_group PlanDoc")
	g_4_KeyBehaviors("WindowsLeftSuppress","ahk_class Shell_TrayWnd")
	g_4_KeyBehaviors("WindowsLeftSuppress","ahk_class WorkerW")
	g_4_KeyBehaviors("WindowsLeftSuppress","Program Manager")
	g_4_KeyBehaviors("WindowsLeftToAltN","Microsoft Excel ahk_class #32770,Do you want to save the changes you made")
	g_4_KeyBehaviors("WindowsLeftToAltN","Microsoft SQL Server Management Studio ahk_class #32770,Save changes to the following items")
	g_4_KeyBehaviors("WindowsLeftToAltN","SciTE ahk_class #32770")
	g_4_KeyBehaviors("WinkeyLefttoAltN","Save ahk_class #32770 ahk_exe notepad++.exe")
	g_4_KeyBehaviors("WinWord","ahk_exe winword.exe")
	g_4_KeyBehaviors("XButton1DoesEscape_WinForm","Commit")
	g_4_KeyBehaviors("XButton1DoesEscape_WinForm","Get Latest Version")
	g_4_KeyBehaviors("XButton2DoesEnter_WinForm","Get Latest Version")
	;Op: Stop
	GroupAdd ActivateIfExist, ahk_group ActivateAndAltNfExist
	GroupAdd AltNifActive, ahk_group ActivateAndAltNfExist
	GroupAdd ActivateIfExist, ahk_group ActivateAndAltF4IfExist
	GroupAdd ActivateIfExist, ahk_group ActivateAndAltFIfExist
	GroupAdd AltF4IfActive, ahk_group ActivateAndAltF4IfExist

	;***************************************************************************************************************
	;/GROUPS********************************************************************************************************
	;***************************************************************************************************************
	prof.Log("Done prepping groups")
	}
}
IsGameActive(){
	IfWinActive ahk_group Games
		return true
	return false
}